// Stranger Things universe: data plan + voice.
// Hawkins, Indiana, 1983-86. Look lives in theme.js; mechanics live in core/.
//
// Lean plan on purpose (credits are tight): ~24 queries, officials first so
// an interrupted run still lands Aisle I intact.

export default {
  id: "stranger-things",
  name: "Hawkins General",

  officialMatch:
    /(stranger things|hellfire club|demogorgon|vecna|starcourt|scoops ahoy|surfer boy|upside down|eggo|hawkins|kate bush|hounds of love|running up that hill|netflix)/i,
  globalExclude:
    /(universit|college|ncaa|nfl|nba|mlb|drapery|curtain|upholstery|by the yard|swatch|valance|toddler|infant|newborn|\bkids?\b|\bboys?\b|\bgirls?\b|dog |pet |phone case|airtag|sticker pack|keychain|halloween costume|cosplay|\bwig\b|party supplies|balloon|cake topper|birthday|ugly christmas sweater|christmas ornament|nightgown|pajama|barbie|hello kitty|sanrio|cinnamoroll|pokemon|disney)/i,
  evidenceIconic:
    /(funko|rise of vecna|hellfire club badge|hounds of love)/i,
  retailerCapPerChapter: 3,
  quoteAfterChapter: 2,

  chapters: [
    { key: "starcourt", numeral: "I", title: "Starcourt", sort: "curated", layout: "ledger",
      intro: "The licensed goods. Shirts, posters, box sets, and the cast at four inches tall." },
    { key: "basement", numeral: "II", title: "The Wheeler Basement", sort: "value", layout: "feature",
      intro: "Ten hours into the campaign. Dice, handbooks, and a channel the adults never check." },
    { key: "byers", numeral: "III", title: "The Byers Living Room", sort: "value", layout: "shelf",
      intro: "String lights, a phone with a cord, waffles for whoever turns up. The wall knows more than it says." },
    { key: "avclub", numeral: "IV", title: "The AV Club", sort: "value", layout: "feature",
      intro: "Tape decks, headphones, instant film. If it takes batteries, it belongs here." },
    { key: "dime", numeral: "V", title: "The Five-and-Dime", sort: "value", layout: "shelf",
      intro: "Ringer tees, denim, tube socks. Dress for a town where nothing ever happens." },
  ],

  queries: [
    // I - Starcourt (official, runs first: credits may not last)
    { chapter: "starcourt", collection: "official", cap: 4,
      query: "Stranger Things t-shirt graphic tee Netflix official",
      note: "The entry point. Hawkins on your chest, no questions at school.",
      price: { min_price: 15, max_price: 80 } },
    { chapter: "starcourt", collection: "official", cap: 2,
      query: "Stranger Things Hellfire Club shirt",
      note: "Club shirt. Attendance is mandatory, socially.",
      include: /hellfire/i,
      price: { min_price: 15, max_price: 80 } },
    { chapter: "starcourt", collection: "official", cap: 4,
      query: "Stranger Things poster print wall art",
      note: "For the bedroom wall, between the bike and the radio.",
      price: { min_price: 12, max_price: 300 } },
    { chapter: "starcourt", collection: "official", cap: 3,
      query: "Funko Pop Stranger Things Eleven Demogorgon Vecna figure",
      note: "The party, four inches tall, holding the line on a shelf.",
      price: { min_price: 8, max_price: 60 } },
    { chapter: "starcourt", collection: "official", cap: 2,
      query: "Stranger Things complete series season DVD Blu-ray box set",
      note: "Every season. Watch with the lights on, or don't.",
      price: { min_price: 10, max_price: 200 } },
    { chapter: "starcourt", collection: "official", cap: 2,
      query: "Stranger Things soundtrack vinyl LP",
      note: "The synth that follows you down the driveway.",
      include: /vinyl|\blp\b|soundtrack/i,
      price: { min_price: 15, max_price: 120 } },
    { chapter: "starcourt", collection: "official", cap: 2,
      query: "Stranger Things Worlds Turned Upside Down official companion book",
      note: "The companion volume. Deeper than the quarry.",
      include: /stranger things/i,
      price: { min_price: 10, max_price: 80 } },
    { chapter: "starcourt", collection: "official", cap: 2,
      query: "Kate Bush Hounds of Love vinyl LP",
      note: "The song that pulls you back. Keep it within reach.",
      include: /kate bush|hounds of love/i,
      price: { min_price: 15, max_price: 120 } },

    // II - The Wheeler Basement
    { chapter: "basement", collection: "in_style", cap: 3,
      query: "Dungeons and Dragons Player's Handbook core rulebook",
      note: "The campaign starts here. Ten hours minimum, no dinner breaks.",
      include: /handbook|rulebook|starter set/i,
      exclude: /hoodie|sweatshirt|t-shirt|\btee\b/i,
      price: { min_price: 15, max_price: 120 } },
    { chapter: "basement", collection: "in_style", cap: 3,
      query: "polyhedral dice set metal DnD tabletop",
      note: "Roll for initiative. The Demogorgon gets a turn too.",
      include: /polyhedral|\bdnd\b|d&d|\brpg\b|dungeons/i,
      price: { min_price: 10, max_price: 120 } },
    { chapter: "basement", collection: "in_style", cap: 3,
      query: "walkie talkie set long range rechargeable",
      note: "Channel six, code red. Over means over.",
      include: /walkie|two.way radio/i,
      price: { min_price: 20, max_price: 250 } },
    { chapter: "basement", collection: "in_style", cap: 3,
      query: "heavy duty metal flashlight incandescent style",
      note: "For the woods past Mirkwood. Batteries are not optional.",
      include: /flashlight|torch/i,
      price: { min_price: 12, max_price: 150 } },

    // III - The Byers Living Room
    { chapter: "byers", collection: "in_style", cap: 2,
      query: "vintage christmas string lights multicolor C9 bulbs indoor",
      note: "One bulb per letter. The wall answers back.",
      include: /light/i,
      exclude: /red and white|icicle/i,
      price: { min_price: 12, max_price: 120 } },
    { chapter: "byers", collection: "in_style", cap: 2,
      query: "retro corded desk telephone classic push button",
      note: "A phone with a cord. It rings when it matters.",
      include: /telephone/i,
      exclude: /\bart\b|print|poster|canvas|cell|mobile|cordless|bluetooth|europe style/i,
      price: { min_price: 20, max_price: 150 } },
    { chapter: "byers", collection: "in_style", cap: 2,
      query: "belgian waffle maker nonstick home breakfast",
      note: "Eggos at home. Leave a box in the woods for a friend.",
      include: /waffle/i,
      exclude: /commercial|bubble|restaurant|\bstick\b|110v|2800w/i,
      price: { min_price: 25, max_price: 150 } },
    { chapter: "byers", collection: "in_style", cap: 2,
      query: "vintage amber glass table lamp living room",
      note: "Sixty watts, left on all night, on purpose.",
      include: /lamp/i,
      exclude: /lava|floor lamp|chandelier/i,
      price: { min_price: 25, max_price: 250 } },

    // IV - The AV Club
    { chapter: "avclub", collection: "in_style", cap: 3,
      query: "portable cassette player walkman retro",
      note: "Side A saves lives. Ask Max.",
      include: /cassette|walkman/i,
      price: { min_price: 20, max_price: 200 } },
    { chapter: "avclub", collection: "in_style", cap: 3,
      query: "boombox cassette player retro 80s portable stereo",
      note: "Loud enough for the cul-de-sac. The Clash approves.",
      include: /boombox|stereo/i,
      price: { min_price: 30, max_price: 300 } },
    { chapter: "avclub", collection: "in_style", cap: 3,
      query: "instant camera instant film retro",
      note: "One shot, sixty seconds, no darkroom.",
      include: /instax|polaroid|instant/i,
      price: { min_price: 40, max_price: 300 } },
    { chapter: "avclub", collection: "in_style", cap: 3,
      query: "retro over ear wired headphones studio",
      note: "Over the ears, over the world. The safest place in Hawkins.",
      include: /headphone/i,
      price: { min_price: 20, max_price: 300 } },

    // V - The Five-and-Dime
    { chapter: "dime", collection: "in_style", cap: 3,
      query: "men's ringer t-shirt retro 70s 80s contrast trim",
      note: "Ringer tees, AV Club spec. Wear it to the science fair.",
      include: /ringer|striped|retro/i,
      gender: "male", price: { min_price: 15, max_price: 100 } },
    { chapter: "dime", collection: "in_style", cap: 3,
      query: "men's denim trucker jacket classic",
      note: "Denim over flannel. The Hawkins layer system.",
      include: /denim|trucker/i,
      exclude: /signature|monogram|logo print/i,
      gender: "male", price: { min_price: 40, max_price: 300 } },
    { chapter: "dime", collection: "in_style", cap: 3,
      query: "men's corduroy jacket shirt jacket",
      note: "Corduroy for October in Indiana. It whistles when you run.",
      include: /corduroy/i,
      gender: "male", price: { min_price: 40, max_price: 300 } },
    { chapter: "dime", collection: "in_style", cap: 2,
      query: "striped tube socks crew retro white",
      note: "Tube socks, pulled high. Standard issue for bike commutes.",
      include: /tube|striped|crew/i,
      exclude: /\bsingle\b/i,
      price: { min_price: 10, max_price: 60 } },
    { chapter: "dime", collection: "in_style", cap: 3,
      query: "canvas high top sneakers classic unisex",
      note: "Canvas high tops. Pedal fast, brake late.",
      include: /canvas|high top/i,
      exclude: /jacquard|\bcamo\b/i,
      price: { min_price: 30, max_price: 150 } },
  ],

  copy: {
    title: "Hawkins General | A Curated Edit of the Stranger Things Universe",
    metaDescription:
      "Stranger Things, bought carefully. The licensed goods, the basement campaign, the Byers living room, and the rest of Hawkins retail, in five aisles.",
    wordmark: `Hawkins <span class="wm-accent">General</span>`,
    mastheadNote: "Hawkins, Indiana",
    kicker: "{count} pieces &middot; five aisles &middot; Hawkins, Indiana, 1983&ndash;86 &middot; updated {updated}",
    h1: `Stock up before the lights <span class="h1-accent">flicker</span>`,
    lede: "Stranger Things, bought carefully. The licensed goods, the campaign table, the Byers living room, and the rest of Hawkins retail: waffles, walkie-talkies, tape decks, denim. Every link goes straight to the retailer.",
    evidenceAria: "Polaroids from Hawkins",
    exhibitLabel: "Snapshot {letter} &middot; Hawkins",
    indexHead: "Shop the aisles",
    chapterLabel: "Aisle",
    ctaVerb: "Grab it at",
    soldOut: "Vanished",
    shelfHint: "Drag sideways. Don't wander off.",
    quote: {
      text: "I am on a curiosity voyage, and I need my paddles to travel.",
      cite: "D. Henderson, Hawkins Middle AV Club",
    },
    footer: {
      recordTitle: "The record",
      recordParagraphs: [
        "Stranger Things&trade; and Netflix are trademarks of their respective owners. Aisle I is the licensed goods. Aisles II through V are the town around them, not licensed product.",
        "Prices and stock come from Channel3 and flicker like everything else in Hawkins; confirm at the retailer.",
      ],
      arrangementTitle: "The arrangement",
      arrangementParagraph:
        "Links are monetized. When you buy through one, this site earns a commission. Friends don't lie.",
    },
  },
};
