// The Sopranos universe: data plan + voice.
// Look lives in theme.js; mechanics live in core/.

export default {
  id: "sopranos",
  name: "Bada Bing & Co.",

  officialMatch:
    /(sopran|bada[\s-]?bing|satriale|gabagool|tony soprano|paulie walnuts|carmela|dr\.? melfi|pine barrens)/i,
  globalExclude:
    /(universit|college|ncaa|nfl|nba|mlb|drapery|curtain|upholstery|by the yard|swatch|valance|toddler|infant|newborn|\bkids?\b|\bboys?\b|\bgirls?\b|dog |pet |phone case|airtag|sticker|keychain charm)/i,
  evidenceIconic:
    /(satriale|bada[\s-]?bing|billboard|cast|tony|complete series|sessions|cabana)/i,
  retailerCapPerChapter: 3,
  quoteAfterChapter: 2,

  collages: [
    { afterChapter: "shrine", label: "From the wardrobe",
      note: "The uniform, previewed. Velour, terry, and the gold that goes over it.",
      pick: /velour|track|terry|robe|silk|cuban|chain|bracelet/i },
    { afterChapter: "gold", label: "After hours",
      note: "The back room and the kitchen. Business gets discussed over these.",
      pick: /humidor|whisk|decanter|poker|ashtray|moka|espresso|pasta/i },
  ],

  chapters: [
    { key: "shrine", numeral: "I", title: "The Shrine", sort: "curated", layout: "ledger",
      intro: "The licensed stuff. For the wall, the shelf, and the record." },
    { key: "wardrobe", numeral: "II", title: "The Wardrobe", sort: "value", layout: "feature",
      intro: "Velour, terry, silk. Dress like you own the block." },
    { key: "gold", numeral: "III", title: "The Gold", sort: "value", layout: "shelf",
      intro: "Worn open-collared, always. The horn keeps the malocchio away." },
    { key: "backroom", numeral: "IV", title: "The Back Room", sort: "value", layout: "feature",
      intro: "Cigars, brown liquor, cards. Business gets discussed after hours." },
    { key: "kitchen", numeral: "V", title: "The Kitchen", sort: "value", layout: "shelf",
      intro: "Sunday gravy is not optional. Neither is the moka pot." },
  ],

  queries: [
    // II — The Wardrobe
    { chapter: "wardrobe", collection: "in_style", cap: 2,
      query: "men's vintage leather car coat jacket",
      note: "For collections.",
      include: /leather|coat/i,
      gender: "male", price: { min_price: 100, max_price: 1500 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's velour tracksuit full zip jacket pants set",
      note: "The uniform for surveying the neighborhood from a lawn chair.",
      include: /velour|velvet/i, exclude: /women|dress\b/i,
      gender: "male", price: { min_price: 40, max_price: 300 } },
    { chapter: "wardrobe", collection: "in_style", cap: 3,
      query: "men's terry cloth robe bathrobe heavyweight",
      note: "For the walk down the driveway to get the paper.",
      include: /terry|towelling|toweling/i,
      gender: "male", price: { min_price: 40, max_price: 300 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's silk camp collar bowling shirt short sleeve",
      note: "Dinner at Vesuvio energy. Worn open, obviously.",
      include: /silk|rayon|camp|bowling|cuban collar/i,
      gender: "male", price: { min_price: 50, max_price: 400 } },
    { chapter: "wardrobe", collection: "in_style", cap: 2,
      query: "men's ribbed cotton tank top undershirt white multipack",
      note: "The load-bearing undershirt of the entire operation.",
      include: /ribbed|tank|a-shirt|undershirt/i,
      gender: "male", price: { min_price: 15, max_price: 80 } },
    { chapter: "wardrobe", collection: "in_style", cap: 3,
      query: "men's retro striped track jacket full zip",
      note: "Paulie's other uniform. Stripes mean seniority.",
      include: /track|striped|retro|zip/i,
      gender: "male", price: { min_price: 35, max_price: 250 } },
    { chapter: "wardrobe", collection: "in_style", cap: 3,
      query: "men's leather driving moccasins loafers",
      note: "You can run in them, but you shouldn't have to.",
      include: /loafer|moccasin|driver|driving/i,
      gender: "male", price: { min_price: 60, max_price: 400 } },

    // III — The Gold
    { chapter: "gold", collection: "in_style", cap: 4,
      query: "men's gold cuban link curb chain necklace",
      note: "Sits over the tank top. Under nothing.",
      include: /cuban|curb|miami|figaro|rope chain/i,
      gender: "male", price: { min_price: 40, max_price: 2500 } },
    { chapter: "gold", collection: "in_style", cap: 3,
      query: "men's gold pinky ring signet",
      note: "The handshake does the talking; the pinky ring confirms it.",
      include: /pinky|signet|ring/i,
      gender: "male", price: { min_price: 40, max_price: 1500 } },
    { chapter: "gold", collection: "in_style", cap: 3,
      query: "cornicello italian horn pendant necklace gold",
      note: "Keeps the malocchio away. Ask your grandmother.",
      include: /cornicello|italian horn|cornetto|horn pendant/i,
      price: { min_price: 20, max_price: 800 } },
    { chapter: "gold", collection: "in_style", cap: 3,
      query: "saint christopher medal pendant necklace gold men",
      note: "Travel protection, old-country issue.",
      include: /saint|st\.?\s|medal|medallion/i,
      price: { min_price: 30, max_price: 800 } },
    { chapter: "gold", collection: "in_style", cap: 3,
      query: "men's gold curb link bracelet heavy",
      note: "The wrist should announce you before you sit down.",
      include: /bracelet/i,
      gender: "male", price: { min_price: 40, max_price: 1500 } },

    // IV — The Back Room
    { chapter: "backroom", collection: "in_style", cap: 4,
      query: "desktop cigar humidor spanish cedar wood",
      note: "For the good ones. You know where they came from.",
      include: /humidor/i,
      price: { min_price: 35, max_price: 600 } },
    { chapter: "backroom", collection: "in_style", cap: 3,
      query: "crystal whiskey glasses set old fashioned lowball",
      note: "Scotch, neat, while somebody explains themselves.",
      include: /whisk|old fashioned|lowball|rocks glass|crystal/i,
      price: { min_price: 25, max_price: 400 } },
    { chapter: "backroom", collection: "in_style", cap: 2,
      query: "crystal whiskey decanter set",
      note: "The bottle stays in the back. The decanter makes the rounds.",
      include: /decanter/i,
      price: { min_price: 40, max_price: 500 } },
    { chapter: "backroom", collection: "in_style", cap: 3,
      query: "professional clay poker chip set case",
      note: "The executive game. Buy-in is not negotiable.",
      include: /poker|chip/i,
      price: { min_price: 40, max_price: 600 } },
    { chapter: "backroom", collection: "in_style", cap: 2,
      query: "heavy glass cigar ashtray large",
      note: "Heavy enough to make a point, technically an ashtray.",
      include: /ashtray/i,
      price: { min_price: 20, max_price: 300 } },

    // V — The Kitchen
    { chapter: "kitchen", collection: "in_style", cap: 2,
      query: "italian prosciutto slicing knife long narrow blade",
      note: "For the gabagool.",
      include: /knife|slic/i,
      price: { min_price: 20, max_price: 200 } },
    { chapter: "kitchen", collection: "in_style", cap: 3,
      query: "bialetti moka pot stovetop espresso maker",
      note: "Coffee the way the old country made it. No machines.",
      include: /moka|bialetti|stovetop espresso/i,
      price: { min_price: 20, max_price: 200 } },
    { chapter: "kitchen", collection: "in_style", cap: 3,
      query: "italian espresso cups saucers set porcelain",
      note: "Espresso after dinner. Decaf is a personal insult.",
      include: /espresso|demitasse/i,
      price: { min_price: 20, max_price: 200 } },
    { chapter: "kitchen", collection: "in_style", cap: 3,
      query: "italian american red sauce cookbook pasta classics",
      note: "Sunday gravy doctrine, in writing.",
      include: /cookbook|recipes|italian|pasta|sauce/i,
      price: { min_price: 15, max_price: 100 } },
    { chapter: "kitchen", collection: "in_style", cap: 2,
      query: "pasta making machine roller stainless",
      note: "Fresh pasta buys forgiveness for almost anything.",
      include: /pasta/i,
      price: { min_price: 40, max_price: 400 } },
    { chapter: "kitchen", collection: "in_style", cap: 2,
      query: "checkered tablecloth red white classic trattoria",
      note: "The tablecloth every serious conversation happens over.",
      include: /checker|gingham|tablecloth/i,
      price: { min_price: 15, max_price: 120 } },

    // I — The Shrine (official)
    { chapter: "shrine", collection: "official", cap: 3,
      query: "The Sopranos Family Cookbook",
      note: "Artie Bucco's finest.",
      price: { min_price: 10, max_price: 100 } },
    { chapter: "shrine", collection: "official", cap: 4,
      query: "The Sopranos Satriale's Bada Bing camp shirt Tombolo capsule",
      note: "The licensed capsule. Satriale's on your chest.",
      price: { min_price: 20 } },
    { chapter: "shrine", collection: "official", cap: 5,
      query: "The Sopranos t-shirt graphic tee HBO official",
      note: "The entry point. Wash cold, air dry, respect it.",
      price: { min_price: 15, max_price: 80 } },
    { chapter: "shrine", collection: "official", cap: 2,
      query: "The Sopranos sweatshirt crewneck Bada Bing hoodie",
      note: "For the colder months at the end of the driveway.",
      price: { min_price: 25, max_price: 120 } },
    { chapter: "shrine", collection: "official", cap: 4,
      query: "The Sopranos poster print wall art framed",
      note: "For the wall. The one everybody asks about.",
      price: { min_price: 15, max_price: 300 } },
    { chapter: "shrine", collection: "official", cap: 4,
      query: "Funko Pop Tony Soprano Paulie Walnuts Silvio television figure",
      note: "The family, four inches tall, watching you work.",
      price: { min_price: 8, max_price: 60 } },
    { chapter: "shrine", collection: "official", cap: 4,
      query: "The Sopranos complete series DVD Blu-ray box set season",
      note: "Eighty-six episodes. The full record.",
      price: { min_price: 10, max_price: 200 } },
    { chapter: "shrine", collection: "official", cap: 3,
      query: "The Sopranos Sessions book Woke Up This Morning",
      note: "The scholarship. Yes, there is scholarship.",
      price: { min_price: 10, max_price: 80 } },
    { chapter: "shrine", collection: "official", cap: 3,
      query: "The Sopranos Bada Bing mug glass barware",
      note: "Morning coffee at the end of the driveway.",
      price: { min_price: 10, max_price: 60 } },
  ],

  copy: {
    title: "Bada Bing & Co. | A Curated Edit of The Sopranos Universe",
    metaDescription:
      "The Sopranos universe, bought carefully. Licensed relics and the North Jersey wardrobe, in five chapters.",
    wordmark: `Bada <span class="wm-accent">Bing</span> &amp; Co.`,
    mastheadNote: "a curated edit",
    kicker: "{count} pieces &middot; five chapters &middot; updated {updated}",
    h1: `Dress like the <span class="h1-accent">family</span>`,
    lede: "The Sopranos universe, bought carefully. Licensed relics and the North Jersey wardrobe around them: velour, gold, cedar, and espresso. Every link goes straight to the retailer.",
    heroCta: { label: "Browse the record", href: "#shrine" },
    evidenceAria: "From the case file",
    exhibitLabel: "Exhibit {letter}",
    indexHead: null,
    chapterLabel: "Chapter",
    ctaVerb: "Shop at",
    soldOut: "Sold out",
    shelfHint: "Drag sideways. Like you mean it.",
    quote: {
      text: "Those who want respect, give respect.",
      cite: "House rule No. 1",
    },
    footer: {
      recordTitle: "The record",
      recordParagraphs: [
        "The Sopranos&trade; and HBO are trademarks of their respective owners. Chapter I is the real, licensed thing. Chapters II through V are inspiration.",
        "Prices and stock come from Channel3 and drift like anything else; confirm at the retailer.",
      ],
      arrangementTitle: "The arrangement",
      arrangementParagraph:
        "Links are monetized. When you buy through one, this site earns a commission. Nobody gets hurt.",
    },
  },
};
