// Breaking Bad universe: data plan + voice.
// Albuquerque, 2008-2013. Look lives in theme.js; mechanics live in core/.
// Conceit: an asset-forfeiture estate sale, catalogued lot by lot.

export default {
  id: "breaking-bad",
  name: "The Heisenberg Estate",

  officialMatch:
    /(breaking\s?bad|heisenberg|los pollos|pollos hermanos|walter white|jesse pinkman|gus(tavo)? fring|schraderbr(a|ä)u|wanna cook|leaves of grass|walt whitman)/i,
  globalExclude:
    /(universit|college|ncaa|nfl|nba|mlb|drapery|curtain|upholstery|by the yard|swatch|valance|toddler|infant|newborn|\bkids?\b|\bboys?\b|\bgirls?\b|dog |pet |phone case|iphone|phone cover|airtag|sticker|keychain charm|better call saul|slippin.? jimmy|kim wexler|halloween costume|cosplay|\bbong\b|\bdab\b|grinder|rolling paper|rolling tray|stash box)/i,
  evidenceIconic:
    /(los pollos|pollos hermanos|heisenberg|complete series|barrel|poster|walter white)/i,
  retailerCapPerChapter: 3,
  quoteAfterChapter: 2,

  chapters: [
    { key: "evidence", numeral: "I", title: "The Evidence", sort: "curated", layout: "ledger",
      intro: "The licensed record, entered as found. Posters, the barrel set, and the book with the inscription." },
    { key: "lab", numeral: "II", title: "The Lab", sort: "value", layout: "feature",
      intro: "Borosilicate and correct procedure. The quality of the coffee is not negotiable." },
    { key: "wardrobe", numeral: "III", title: "The Wardrobe", sort: "value", layout: "shelf",
      intro: "Pork pie felt, tan cotton, one pair of glasses. Mild until it is not." },
    { key: "the505", numeral: "IV", title: "The 505", sort: "value", layout: "feature",
      intro: "Hatch green, pinon smoke, To'hajiilee light. The desert keeps what it is given." },
    { key: "carwash", numeral: "V", title: "The Car Wash", sort: "value", layout: "shelf",
      intro: "A1 since day one. Cash preferred, questions discouraged." },
  ],

  queries: [
    // I — The Evidence (official)
    { chapter: "evidence", collection: "official", cap: 5,
      query: "Breaking Bad t-shirt Los Pollos Hermanos Heisenberg graphic tee",
      note: "The entry point. Somebody at the car wash will nod at you.",
      price: { min_price: 15, max_price: 80 } },
    { chapter: "evidence", collection: "official", cap: 4,
      query: "Breaking Bad poster print wall art framed",
      note: "For the wall behind the desk. It sets a tone.",
      price: { min_price: 12, max_price: 300 } },
    { chapter: "evidence", collection: "official", cap: 4,
      query: "Breaking Bad complete series Blu-ray DVD box set",
      note: "The chemical record, sold by the season.",
      price: { min_price: 10, max_price: 250 } },
    { chapter: "evidence", collection: "official", cap: 4,
      query: "Funko Pop Breaking Bad Walter White Jesse Pinkman Gus Fring figure",
      note: "The operation, four inches tall, staring back.",
      price: { min_price: 8, max_price: 60 } },
    { chapter: "evidence", collection: "official", cap: 3,
      query: "Breaking Bad hoodie sweatshirt Los Pollos Hermanos crewneck",
      note: "For early shifts at the chicken place.",
      exclude: /\bugly\b/i,
      price: { min_price: 25, max_price: 120 } },
    { chapter: "evidence", collection: "official", cap: 2,
      query: "Wanna Cook Breaking Bad companion book episode guide",
      note: "The scholarship. Peer reviewed by the fandom.",
      include: /wanna cook|breaking bad 101/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "evidence", collection: "official", cap: 2,
      query: "The Science of Breaking Bad book chemistry",
      note: "The chemistry, checked by people with tenure.",
      include: /science of breaking bad/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "evidence", collection: "official", cap: 3,
      query: "Leaves of Grass Walt Whitman hardcover",
      note: "To my other favorite W.W. Keep it out of the bathroom.",
      include: /leaves of grass|whitman/i,
      exclude: /illustrated|children|selected poems/i,
      price: { min_price: 8, max_price: 80 } },
    { chapter: "evidence", collection: "official", cap: 3,
      query: "Breaking Bad Los Pollos Hermanos mug coffee cup",
      note: "Coffee at the office. The other office.",
      price: { min_price: 10, max_price: 60 } },

    // II — The Lab
    { chapter: "lab", collection: "in_style", cap: 4,
      query: "chemex pour over glass coffee maker",
      note: "Gale had opinions about extraction. Gale was right.",
      include: /chemex|pour.?over/i,
      exclude: /print|poster|canvas|wall art/i,
      price: { min_price: 20, max_price: 200 } },
    { chapter: "lab", collection: "in_style", cap: 4,
      query: "borosilicate glass beaker set graduated laboratory",
      note: "99.1 percent begins with clean glassware.",
      include: /beaker|borosilicate|graduated cylinder/i,
      exclude: /polypropylene|plastic|non.?sterile|measuring cup|kitchen|measurement|ultnice/i,
      price: { min_price: 10, max_price: 120 } },
    { chapter: "lab", collection: "in_style", cap: 3,
      query: "erlenmeyer flask glass set laboratory",
      note: "The silhouette of the whole enterprise.",
      include: /erlenmeyer|kjeldahl|volumetric|boiling flask|round.?bottom/i,
      exclude: /hip flask|whiskey|whisky|yeti|thermos/i,
      price: { min_price: 10, max_price: 120 } },
    { chapter: "lab", collection: "in_style", cap: 3,
      query: "periodic table poster print vintage science wall art",
      note: "The full alphabet. Two letters matter.",
      include: /periodic|element/i, exclude: /no embellishment/i,
      price: { min_price: 12, max_price: 200 } },
    { chapter: "lab", collection: "in_style", cap: 2,
      query: "chemistry lab safety goggles splash protection",
      note: "Safety first. Ask anyone who skipped it.",
      include: /goggle/i,
      exclude: /learning resources|children|kids|toy/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "lab", collection: "in_style", cap: 3,
      query: "laboratory notebook graph paper hardcover",
      note: "Neat handwriting has consequences.",
      include: /lab(oratory)?\s?notebook|graph paper notebook|composition book|scientific notebook/i,
      price: { min_price: 10, max_price: 80 } },

    // III — The Wardrobe
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's pork pie hat wool felt black",
      note: "The hat negotiates. You just stand there.",
      include: /pork\s?pie/i,
      gender: "male", price: { min_price: 20, max_price: 200 } },
    { chapter: "wardrobe", collection: "in_style", cap: 3,
      query: "men's browline clubmaster sunglasses classic",
      note: "For the glare. Both kinds.",
      include: /browline|clubmaster|sunglass/i,
      gender: "male", price: { min_price: 15, max_price: 300 } },
    { chapter: "wardrobe", collection: "in_style", cap: 3,
      query: "men's tan harrington jacket windbreaker zip",
      note: "High school faculty issue. Deceptively mild.",
      include: /harrington|windbreaker|jacket/i,
      gender: "male", price: { min_price: 40, max_price: 300 } },
    { chapter: "wardrobe", collection: "in_style", cap: 2,
      query: "men's white cotton briefs multipack classic",
      note: "For standing in the desert. Pants optional.",
      include: /brief/i, exclude: /boxer/i,
      gender: "male", price: { min_price: 10, max_price: 60 } },
    { chapter: "wardrobe", collection: "in_style", cap: 3,
      query: "men's oversized zip up hoodie streetwear baggy",
      note: "Two sizes up. Pinkman doctrine.",
      include: /hood/i,
      exclude: /crystal|rhinestone|bling|stud/i,
      gender: "male", price: { min_price: 30, max_price: 150 } },
    { chapter: "wardrobe", collection: "in_style", cap: 2,
      query: "men's knit beanie cuffed skull cap",
      note: "Winter spec, yo.",
      include: /beanie|knit cap|skull cap/i,
      exclude: /embroider|custom|personaliz/i,
      gender: "male", price: { min_price: 8, max_price: 60 } },

    // IV — The 505
    { chapter: "the505", collection: "in_style", cap: 4,
      query: "hatch green chile roasted new mexico",
      note: "The state question, answered.",
      include: /hatch|green chile/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "the505", collection: "in_style", cap: 3,
      query: "new mexico pinon coffee dark roast ground",
      note: "Pinon roast. Breakfast is important.",
      include: /pi(n|ñ)on|new mexico/i,
      price: { min_price: 8, max_price: 50 } },
    { chapter: "the505", collection: "in_style", cap: 4,
      query: "southwestern serape falsa blanket woven",
      note: "For the trunk of a car you paid cash for.",
      include: /serape|southwest|falsa|saltillo|baja/i,
      exclude: /\bking\b|\btwin\b|\bqueen\b/i,
      price: { min_price: 15, max_price: 250 } },
    { chapter: "the505", collection: "in_style", cap: 3,
      query: "turquoise bolo tie western silver",
      note: "New Mexico formalwear.",
      include: /bolo/i,
      price: { min_price: 15, max_price: 300 } },
    { chapter: "the505", collection: "in_style", cap: 4, allowZero: true,
      query: "new mexico desert landscape art print",
      note: "To'hajiilee light. Coordinates not included.",
      include: /new mexico|desert|mesa|adobe|santa fe|albuquerque/i,
      exclude: /california|joshua tree|arizona|sahara|utah|moab|cactus|saguaro|palm|monument valley/i,
      price: { min_price: 12, max_price: 300 } },
    { chapter: "the505", collection: "in_style", cap: 3,
      query: "new mexico cookbook green chile recipes southwest",
      note: "Red or green is a serious question. The answer is Christmas.",
      include: /new mexico|southwest|chile|santa fe/i,
      price: { min_price: 10, max_price: 80 } },

    // V — The Car Wash
    { chapter: "carwash", collection: "in_style", cap: 4,
      query: "car detailing kit wash exterior complete",
      note: "Have an A1 day.",
      include: /detail|wash/i,
      exclude: /\bboat\b|marine/i,
      price: { min_price: 20, max_price: 150 } },
    { chapter: "carwash", collection: "in_style", cap: 3,
      query: "microfiber car drying towels pack",
      note: "Lint-free, streak-free, question-free.",
      include: /microfiber/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "carwash", collection: "in_style", cap: 3,
      query: "foam cannon car wash soap kit",
      note: "Thick coverage, honest work.",
      include: /foam cannon|snow foam|car wash soap|car shampoo|car soap/i,
      price: { min_price: 15, max_price: 120 } },
    { chapter: "carwash", collection: "in_style", cap: 3,
      query: "black duffel bag heavy duty large canvas",
      note: "Fits exactly what you think it fits.",
      include: /duffel|duffle/i,
      exclude: /embroider|personaliz|monogram|\bname\b|backpack/i,
      price: { min_price: 25, max_price: 200 } },
    { chapter: "carwash", collection: "in_style", cap: 2,
      query: "handheld car vacuum high power cordless",
      note: "If it can't be fixed, ask for Ed.",
      include: /vacuum/i, exclude: /\busb\b/i,
      price: { min_price: 20, max_price: 150 } },
    { chapter: "carwash", collection: "in_style", cap: 2,
      query: "car air freshener pine tree hanging pack",
      note: "Pine. It covers most things.",
      include: /air freshener|little trees?|\bpine\b/i,
      price: { min_price: 8, max_price: 40 } },
  ],

  copy: {
    title: "The Heisenberg Estate | A Curated Edit of the Breaking Bad Universe",
    metaDescription:
      "Breaking Bad, bought carefully. The seized record and the New Mexico that produced it, catalogued in five lots.",
    wordmark: `The <span class="wm-accent">Heisenberg</span> Estate`,
    mastheadNote: "everything must go",
    kicker: "{count} pieces &middot; five lots &middot; Albuquerque, 2008&ndash;2013 &middot; updated {updated}",
    h1: `Say my <span class="h1-accent">name</span>`,
    lede: "Breaking Bad, bought carefully. The seized record and the New Mexico that produced it: borosilicate, pork pie felt, hatch green, microfiber. Every link goes straight to the retailer.",
    evidenceAria: "From the seizure",
    exhibitLabel: "Exhibit {letter} &middot; DEA",
    indexHead: "Catalog of lots",
    chapterLabel: "Lot",
    ctaVerb: "Acquire at",
    soldOut: "Seized",
    shelfHint: "Drag sideways. No half measures.",
    quote: {
      text: "I am the one who knocks.",
      cite: "W. White, to his wife",
    },
    footer: {
      recordTitle: "The record",
      recordParagraphs: [
        "Breaking Bad&trade;, AMC, and Sony Pictures Television are trademarks of their respective owners. Lot I is the licensed record. Lots II through V are the world around it, not licensed product.",
        "Prices and stock come from Channel3 and drift like everything else; confirm at the retailer.",
      ],
      arrangementTitle: "The arrangement",
      arrangementParagraph:
        "Links are monetized. When you buy through one, this site earns a commission. It goes in the barrel.",
    },
  },
};
