// True Detective S1 universe: data plan + voice.
// Louisiana, 1995–2012. Look lives in theme.js; mechanics live in core/.

export default {
  id: "true-detective",
  name: "Carcosa Outfitters",

  officialMatch:
    /(true detective|rust cohle|marty hart|carcosa|yellow king|king in yellow|flat circle|far from any road|handsome family|pizzolatto|ligotti|conspiracy against the human race|hbo)/i,
  globalExclude:
    /(universit|college|ncaa|nfl|nba|mlb|drapery|curtain|upholstery|by the yard|swatch|valance|toddler|infant|newborn|\bkids?\b|\bboys?\b|\bgirls?\b|dog |pet |phone case|airtag|sticker pack|halloween costume|christmas|night country|season 4|chelsea detective)/i,
  evidenceIconic:
    /(flat circle|carcosa|yellow king|king in yellow|poster|rust)/i,
  retailerCapPerChapter: 3,
  quoteAfterChapter: 2,

  chapters: [
    { key: "casefile", numeral: "I", title: "The Case File", sort: "curated", layout: "ledger",
      intro: "The on-the-nose stuff. Shirts, posters, the tapes, the book that started the dread." },
    { key: "kit", numeral: "II", title: "The Detective's Kit", sort: "value", layout: "feature",
      intro: "Flask, lighter, ledger. Tools for the long nights of looking." },
    { key: "carcosa", numeral: "III", title: "Carcosa", sort: "value", layout: "shelf",
      intro: "Antlers, twig work, black stars. Decorative, allegedly." },
    { key: "bayou", numeral: "IV", title: "The Bayou", sort: "value", layout: "feature",
      intro: "Chicory, cayenne, sepia light. The Louisiana that swallowed them." },
    { key: "wardrobe", numeral: "V", title: "The Wardrobe", sort: "value", layout: "shelf",
      intro: "Flannel, chambray, worn leather. Dress for fieldwork in 1995." },
  ],

  queries: [
    // I — The Case File (official)
    { chapter: "casefile", collection: "official", cap: 4,
      query: "True Detective poster print season one Carcosa art",
      note: "For the wall you stare at when it all connects.",
      price: { min_price: 12, max_price: 300 } },
    { chapter: "casefile", collection: "official", cap: 4,
      query: "True Detective TV poster McConaughey Harrelson series",
      note: "The two of them, before the years got in.",
      price: { min_price: 12, max_price: 300 } },
    { chapter: "casefile", collection: "official", cap: 4,
      query: "True Detective season one DVD Blu-ray HBO",
      note: "Eight episodes. The whole confession.",
      exclude: /chelsea|night country|season 4/i,
      price: { min_price: 8, max_price: 150 } },
    { chapter: "casefile", collection: "official", cap: 4,
      query: "The King in Yellow Robert Chambers book paperback",
      note: "The 1895 book behind the dread. Public domain, private consequences.",
      price: { min_price: 8, max_price: 60 } },
    { chapter: "casefile", collection: "official", cap: 2,
      query: "Galveston novel Nic Pizzolatto paperback",
      note: "The creator's novel. Same swamp, different bodies.",
      include: /galveston|pizzolatto/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "casefile", collection: "official", cap: 2,
      query: "The Conspiracy Against the Human Race Thomas Ligotti book",
      note: "The philosophy Rust was quoting. Read at your own pace.",
      price: { min_price: 8, max_price: 80 } },

    // II — The Detective's Kit
    { chapter: "kit", collection: "in_style", cap: 4,
      query: "classic chrome zippo lighter windproof",
      note: "A light in the dark. Literal, for once.",
      include: /zippo|lighter/i,
      exclude: /harley|daddy|\bdad\b|\bmom\b|wedding|groomsman|anniversary/i,
      price: { min_price: 15, max_price: 120 } },
    { chapter: "kit", collection: "in_style", cap: 4,
      query: "stainless steel hip flask leather wrapped",
      note: "For the passenger seat. Off duty, technically.",
      include: /flask/i,
      price: { min_price: 15, max_price: 150 } },
    { chapter: "kit", collection: "in_style", cap: 4,
      query: "black leather journal notebook refillable",
      note: "Rust kept a ledger. Keep yours.",
      include: /journal|notebook|ledger/i,
      price: { min_price: 15, max_price: 150 } },
    { chapter: "kit", collection: "in_style", cap: 4,
      query: "men's aviator sunglasses gold frame classic",
      note: "State-issued squint. 1995 spec.",
      include: /aviator|sunglass/i,
      gender: "male", price: { min_price: 20, max_price: 300 } },
    { chapter: "kit", collection: "in_style", cap: 4,
      query: "stainless steel vacuum thermos bottle classic",
      note: "Coffee that outlasts the stakeout.",
      include: /thermos|vacuum|bottle|flask/i,
      price: { min_price: 20, max_price: 150 } },
    { chapter: "kit", collection: "in_style", cap: 2,
      query: "portable voice recorder cassette interview",
      note: "For statements. People say things.",
      include: /record|cassette|dictaphone/i,
      price: { min_price: 25, max_price: 250 } },
    { chapter: "kit", collection: "in_style", cap: 2,
      query: "men's cross pendant necklace silver simple",
      note: "The one thing on Rust's wall. Bare, like the apartment.",
      include: /cross|crucifix/i,
      price: { min_price: 20, max_price: 400 } },

    // III — Carcosa
    { chapter: "carcosa", collection: "in_style", cap: 4,
      query: "deer antler decor sculpture natural shed",
      note: "The crown from the cane fields. Decorative, allegedly.",
      include: /antler|horn|deer/i,
      exclude: /decoy|hunting|taxidermy form|sheep|\bram\b|target/i,
      price: { min_price: 20, max_price: 400 } },
    { chapter: "carcosa", collection: "in_style", cap: 4,
      query: "natural twig branch sculpture decor handmade rustic",
      note: "Twig work. Ask no further questions.",
      include: /twig|branch|willow|rattan|driftwood/i,
      price: { min_price: 15, max_price: 300 } },
    { chapter: "carcosa", collection: "in_style", cap: 4,
      query: "ouroboros snake ring jewelry sterling",
      note: "The snake eats its tail. Time does the same.",
      include: /ouroboros|serpent|snake/i,
      price: { min_price: 25, max_price: 500 } },
    { chapter: "carcosa", collection: "in_style", cap: 4,
      query: "black taper candles set unscented",
      note: "Mood lighting for unresolved cases.",
      include: /candle/i,
      price: { min_price: 10, max_price: 100 } },
    { chapter: "carcosa", collection: "in_style", cap: 4,
      query: "tarot deck classic Rider Waite",
      note: "The ladies at the laundromat had opinions.",
      include: /tarot|oracle/i,
      price: { min_price: 12, max_price: 100 } },
    { chapter: "carcosa", collection: "in_style", cap: 2,
      query: "bird skull raven skull replica decor resin",
      note: "A conversation piece. The conversation is short.",
      include: /skull/i,
      price: { min_price: 12, max_price: 200 } },
    { chapter: "carcosa", collection: "in_style", cap: 4,
      query: "abstract black spiral art print minimal dark",
      note: "The spiral. You've seen it before, you'll see it again.",
      include: /spiral|abstract|black/i,
      price: { min_price: 15, max_price: 300 } },

    // IV — The Bayou
    { chapter: "bayou", collection: "in_style", cap: 4, allowZero: true,
      query: "louisiana swamp cypress trees wall art canvas print",
      note: "Sepia water, cypress knees, no witnesses.",
      include: /louisiana|bayou|swamp|atchafalaya|new orleans/i,
      exclude: /california|van gogh|provence/i,
      price: { min_price: 15, max_price: 400 } },
    { chapter: "bayou", collection: "in_style", cap: 4,
      query: "cajun creole cookbook new orleans recipes",
      note: "Gumbo doctrine. Respect the roux.",
      include: /cajun|creole|new orleans|louisiana|gumbo/i,
      price: { min_price: 12, max_price: 80 } },
    { chapter: "bayou", collection: "in_style", cap: 4,
      query: "chicory coffee new orleans dark roast ground",
      note: "New Orleans coffee, black. Sleep is a choice.",
      include: /chicory|new orleans|coffee/i,
      price: { min_price: 8, max_price: 60 } },
    { chapter: "bayou", collection: "in_style", cap: 4,
      query: "louisiana hot sauce gift set cayenne",
      note: "Heat with paperwork. Handle accordingly.",
      include: /hot sauce|cayenne|pepper sauce|louisiana/i,
      price: { min_price: 10, max_price: 80 } },
    { chapter: "bayou", collection: "in_style", cap: 4,
      query: "moss green scented candle woods bergamot",
      note: "Smells like the treeline at dusk. In a good way, mostly.",
      include: /candle/i,
      price: { min_price: 15, max_price: 120 } },
    { chapter: "bayou", collection: "in_style", cap: 2,
      query: "men's waxed canvas rain jacket field",
      note: "It rains on the just and the unjust. Mostly here.",
      include: /wax|rain|field|canvas/i,
      gender: "male", price: { min_price: 60, max_price: 500 } },

    // V — The Wardrobe
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's heavyweight flannel shirt plaid work",
      note: "Fieldwork flannel. Sleeves roll for digging.",
      include: /flannel|plaid/i,
      gender: "male", price: { min_price: 30, max_price: 250 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's chambray work shirt long sleeve",
      note: "CID casual. Iron optional after year three.",
      include: /chambray|work shirt|denim shirt/i,
      gender: "male", price: { min_price: 30, max_price: 250 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's heavyweight plain grey t-shirt cotton",
      note: "The Cohle base layer. No graphics, no comment.",
      include: /tee|t-shirt|shirt/i,
      gender: "male", price: { min_price: 15, max_price: 100 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's vintage leather jacket rugged",
      note: "Worn like the years wore him.",
      include: /leather/i,
      gender: "male", price: { min_price: 80, max_price: 900 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's western leather belt brass buckle",
      note: "Louisiana state standard. Holds more than pants.",
      include: /belt/i,
      gender: "male", price: { min_price: 25, max_price: 250 } },
    { chapter: "wardrobe", collection: "in_style", cap: 4,
      query: "men's leather work boots moc toe",
      note: "For ground that keeps secrets.",
      include: /boot/i,
      gender: "male", price: { min_price: 60, max_price: 500 } },
    { chapter: "wardrobe", collection: "in_style", cap: 2,
      query: "plain trucker cap mesh snapback blank",
      note: "Marty's off-duty thinking cap.",
      include: /cap|hat|trucker/i,
      price: { min_price: 10, max_price: 80 } },
  ],

  copy: {
    title: "Carcosa Outfitters | A Curated Edit of the True Detective Universe",
    metaDescription:
      "True Detective, season one, bought carefully. The case file, the detective's kit, and the Louisiana around them, in five files.",
    wordmark: `<span class="wm-accent">Carcosa</span> Outfitters`,
    mastheadNote: "season one, an edit",
    kicker: "{count} pieces &middot; five files &middot; Louisiana, 1995&ndash;2012 &middot; updated {updated}",
    h1: `Step into the <span class="h1-accent">flat circle</span>`,
    lede: "True Detective, season one, bought carefully. The case file, the detective's kit, and the Louisiana that swallowed them: sulfur, cedar, chicory, and bone. Every link goes straight to the retailer.",
    evidenceAria: "From the case file",
    exhibitLabel: "Exhibit {letter} &middot; CID",
    indexHead: "Explore the evidence",
    chapterLabel: "File",
    ctaVerb: "Examine at",
    soldOut: "Gone",
    shelfHint: "Drag sideways. Follow the thread.",
    quote: {
      text: "The world needs bad men. We keep the other bad men from the door.",
      cite: "Det. R. Cohle, Louisiana CID",
    },
    footer: {
      recordTitle: "The record",
      recordParagraphs: [
        "True Detective&trade; and HBO are trademarks of their respective owners. File I is the on-the-nose material. Files II through V are the world around it, not licensed product.",
        "Prices and stock come from Channel3 and drift like everything else; confirm at the retailer.",
      ],
      arrangementTitle: "The arrangement",
      arrangementParagraph:
        "Links are monetized. When you buy through one, this site earns a commission. Nothing is ever over.",
    },
  },
};
